### ISSUE TITLE
[QUESTIONS/COMMENTS] Forum for any implementation issues...

### ISSUE THREAD

**Issue by wkarney** [wkarney/minted-export#4]
**Questions or Comments**

Let me know if you are encountering any difficulties with making the scripts work on your machine here and I can help troubleshoot!

**Comment by lenoxbooks** [comment]
Hey, thanks for putting this together. Any ideas on what could be causing this:

`Traceback (most recent call last):
  File "minted_api_request.py", line 47, in <module>
    address_book = pd.DataFrame(listings)
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 468, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 283, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 78, in arrays_to_mgr
    index = extract_index(arrays)
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 387, in extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index`

**Comment by wkarney** [comment]
I think your username and password were not entered correctly.  If the correct credentials are not entered then the response will return: `{'detail': 'Authentication credentials were not provided.'}`. And Pandas will raise an exception when trying to convert that into a data frame in line 47.

**Comment by maniscalcojohn** [comment]
Thanks for your help with this. I am having an issue installing the Panda dependency. Running Python 3.9. Here is my error: 

> Failed to build pandas
> ERROR: Could not build wheels for pandas which use PEP 517 and cannot be installed directly

**Comment by wkarney** [comment]
Glad you got it working any glad it helped! @maniscalcojohn
